language: node_js

install:
 - npm install
 - npm install --only=dev
 - npm install codecov nyc -g

node_js:
 - '7'
 - '9'

script:
 - nyc mocha

after_success:
 - codecov -f ./coverage/coverage-final.json