language: node_js

install:
 - npm install
 - npm install --only=dev

node_js:
 - '7'
 - '9'

script: 
 - npm install codecov nyc -g
 - nyc mocha

after_success:
 - codecov -f coverage\coverage-final.json